import pandas as pd
import numpy as np

line_items = [
    {"leg_id": "2402",
     "departure_port_code": "GRU",
     "departure_city": "Sao Paulo",
     "departure_country_code": "BR",
     "arrival_port_code": "SDU",
     "arrival_city": "Rio de Janeiro",
     "arrival_country_code": "BR",
     "departure_date": "2017-06-20T12:10:00+02:00",
     "arrival_date": "2017-06-20T13:15:00+02:00",
     "carrier_code": "AD",
     "route_index": 1,
     "leg_index": 1,
     "ticket_class": "Economy",
     "transport_method": "plane",
     "title": "Flight tickets GRU-SDU",
     "price": 188.125,
     "product_id": "Flight GRU - SDU False",
     "quantity": 1,
     "requires_shipping": false,
     "sku": "FOKMEKD",
     "category": "Flight",
     "product_type": "travel",
     "brand": "Azul"},

    {"leg_id": "4356",
     "departure_port_code": "GIG",
     "departure_city": "Rio de Janeiro",
     "departure_country_code": "BR",
     "arrival_port_code": "VCP",
     "arrival_city": "Campinas",
     "arrival_country_code": "BR",
     "departure_date": "2017-08-30T06:10:00+02:00",
     "arrival_date": "2017-08-30T07:25:00+02:00",
     "carrier_code": "AD",
     "route_index": 2,
     "leg_index": 2,
     "ticket_class": "Economy",
     "transport_method": "plane",
     "title": "Flight tickets GIG-VCP",
     "Price": 188.125,
     "product_id": "Flight GRU - SDU False",
     "quantity": 1,
     "requires_shipping": false,
     "sku": "FOKMEKD",
     "category": "Flight",
     "product_type": "travel",
     "brand": "Azul"}]


